import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from "react";
import { groth16 } from 'snarkjs';
const ethers = require("ethers");

export default function Home() {
  const [salt, setsalt] = useState();





  return (
    <div className={styles.container}>
      <Head>
        <title>Board Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div style={{ width: 50 }} >
          <button
            className={styles.button}
            onClick={async () => {
              console.log("click")
              setsalt(ethers.utils.randomBytes(32).toString())

              const input = {
                a: 0,
                b: 5,
                salt: 10,
                zone: 1
              }

              console.log("Input", input);
              const { proof, publicSignals } = await groth16.fullProve(input, "/Register.wasm", "/Register_final.zkey");
              console.log("proof", proof);
              console.log("publicSignal", publicSignals);



            }}


          >
            Click
          </button>

        </div>






      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
