import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Entergame from "../components/Entergame";
const ethers = require("ethers");
const groth16 = require("snarkjs").groth16;

export default function Home() {
  const [salt, setsalt] = useState();

  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <title>Board Game</title>
        <div className=" bg-black w-screen h-screen flex justify-center items-center ">
          <Entergame />
        </div>
      </main>
    </div>
  );
}
